
development:
  adapter: postgresql
  database: project_development
  username: postgres
  password: postgres
  min_messages: warning
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: project_test
  username: postgres
  password: postgres
  min_messages: warning
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: project_production
  username: postgres
  password: postgres
  min_messages: warning
  host: localhost
  port: 5432